#!/bin/sh
# shellcheck disable=SC2016,SC2329
# M11-01a verification. Generated by tools/bundle.py from the
# ROADMAP.md row at line 362 (D-114). Do not edit by
# hand: edit the roadmap row and regenerate.
#
# Takes one argument, container or host, and runs only that part
# (D-086). Prints status: DONE as its last line on success and
# status: PENDING otherwise.
set -eu

task_dir=$(dirname "$0")
fail=0

# A command carrying a <placeholder> needs an operator substitution, so
# it is not run here; its filed evidence is what proves it instead.
run_cmd() {
  case $1 in
    *'<'*'>'*)
      printf '%s\n' "skip (needs substitution): $1"
      return 0
      ;;
  esac
  printf '%s\n' "run: $1"
  if sh -c "$1"; then
    printf '%s\n' "ok: $1"
  else
    printf '%s\n' "FAILED: $1"
    fail=1
  fi
}

need_evidence() {
  if [ ! -s "$task_dir/$1" ]; then
    printf '%s\n' "missing evidence: $1"
    fail=1
    return 0
  fi
  if [ -n "$2" ] && ! grep -q -- "$2" "$task_dir/$1"; then
    printf '%s\n' "evidence $1 does not contain: $2"
    fail=1
  fi
}

finish() {
  if [ "$fail" -eq 0 ]; then
    printf '%s\n' "status: DONE"
    exit 0
  fi
  printf '%s\n' "status: PENDING"
  exit 1
}

part=${1:-}
case "$part" in
  container)
    printf '%s\n' "no container part for this task" # host row (D-061)
    finish
    ;;
  host)
    run_cmd 'gh run view <id> --json jobs --jq '\''.jobs[] | select(.name=="ci-required") | .labels'\'''
    run_cmd 'gh pr view <n> -R jackin-project/jackin --json state --jq .state'
    run_cmd 'gh release view preview --repo jackin-project/jackin --json targetCommitish --jq .targetCommitish'
    run_cmd 'git rev-parse origin/main'
    run_cmd 'jackin-role'
    run_cmd 'gh release download preview --pattern '\''jackin-<host target>.tar.gz'\'''
    run_cmd 'jackin-role validate .'
    run_cmd 'gh run watch "$(cat tasks/M11-01a/run-<p>.txt)" -R donbeave/jackin-crew-<p> --exit-status'
    run_cmd 'gh run view "$(cat tasks/M11-01a/run-<p>.txt)" -R donbeave/jackin-crew-<p> --json status,conclusion | jq -e '\''.status=="completed" and .conclusion=="success"'\'''
    need_evidence 'squash-body.md' ''
    finish
    ;;
  *)
    printf '%s\n' "usage: $0 container|host"
    printf '%s\n' "status: PENDING"
    exit 2
    ;;
esac
