#!/bin/sh
# shellcheck disable=SC2016,SC2329
# M1-13 verification. Generated by tools/bundle.py from the
# ROADMAP.md row at line 147 (D-114). Do not edit by
# hand: edit the roadmap row and regenerate.
#
# Takes one argument, container or host, and runs only that part
# (D-086). Prints status: DONE as its last line on success and
# status: PENDING otherwise.
set -eu

task_dir=$(dirname "$0")
fail=0

# A command carrying a <placeholder> needs an operator substitution, so
# it is not run here; its filed evidence is what proves it instead.
run_cmd() {
  case $1 in
    *'<'*'>'*)
      printf '%s\n' "skip (needs substitution): $1"
      return 0
      ;;
  esac
  printf '%s\n' "run: $1"
  if sh -c "$1"; then
    printf '%s\n' "ok: $1"
  else
    printf '%s\n' "FAILED: $1"
    fail=1
  fi
}

need_evidence() {
  if [ ! -s "$task_dir/$1" ]; then
    printf '%s\n' "missing evidence: $1"
    fail=1
    return 0
  fi
  if [ -n "$2" ] && ! grep -q -- "$2" "$task_dir/$1"; then
    printf '%s\n' "evidence $1 does not contain: $2"
    fail=1
  fi
}

finish() {
  if [ "$fail" -eq 0 ]; then
    printf '%s\n' "status: DONE"
    exit 0
  fi
  printf '%s\n' "status: PENDING"
  exit 1
}

part=${1:-}
case "$part" in
  container)
    printf '%s\n' "no container part for this task" # host row (D-061)
    finish
    ;;
  host)
    run_cmd 'jackin load <role> probe-L<n> --dry-run --format json'
    run_cmd 'jackin usage cache accounts --format json'
    run_cmd 'docker info'
    run_cmd 'jq -e '\''keys==["L1","L2","L3","L4","L5","L6"] and all(.[]; .model_id!="" and .effort=="medium" and .label==("model:"+.model_id))'\'' tasks/M1-13/lanes.json'
    run_cmd 'gh pr view <n> -R jackin-project/jackin-the-architect --json state --jq .state'
    run_cmd 'gh api repos/jackin-project/jackin-the-architect/contents/.github/workflows/ci.yml --jq .content | base64 -d | grep -c velnor-target-mvp'
    run_cmd 'git show origin/main:jackin.role.toml'
    run_cmd 'gh api repos/jackin-project/jackin-the-architect/branches/feat/managed-execution'
    need_evidence 'dind.out' ''
    need_evidence 'lanes.json' ''
    finish
    ;;
  *)
    printf '%s\n' "usage: $0 container|host"
    printf '%s\n' "status: PENDING"
    exit 2
    ;;
esac
