#!/bin/sh
# shellcheck disable=SC2016,SC2329
# M1-05b verification. Generated by tools/bundle.py from the
# ROADMAP.md row at line 137 (D-114). Do not edit by
# hand: edit the roadmap row and regenerate.
#
# Takes one argument, container or host, and runs only that part
# (D-086). Prints status: DONE as its last line on success and
# status: PENDING otherwise.
set -eu

task_dir=$(dirname "$0")
fail=0

# A command carrying a <placeholder> needs an operator substitution, so
# it is not run here; its filed evidence is what proves it instead.
run_cmd() {
  case $1 in
    *'<'*'>'*)
      printf '%s\n' "skip (needs substitution): $1"
      return 0
      ;;
  esac
  printf '%s\n' "run: $1"
  if sh -c "$1"; then
    printf '%s\n' "ok: $1"
  else
    printf '%s\n' "FAILED: $1"
    fail=1
  fi
}

need_evidence() {
  if [ ! -s "$task_dir/$1" ]; then
    printf '%s\n' "missing evidence: $1"
    fail=1
    return 0
  fi
  if [ -n "$2" ] && ! grep -q -- "$2" "$task_dir/$1"; then
    printf '%s\n' "evidence $1 does not contain: $2"
    fail=1
  fi
}

finish() {
  if [ "$fail" -eq 0 ]; then
    printf '%s\n' "status: DONE"
    exit 0
  fi
  printf '%s\n' "status: PENDING"
  exit 1
}

part=${1:-}
case "$part" in
  container)
    run_cmd 'jackin role validate && ! grep -qE '\''^[env.OP_SERVICE_ACCOUNT_TOKEN]'\'' jackin.role.toml && ! grep -qE '\''^model *='\'' jackin.role.toml && grep -q AGENT_BROWSER_EXECUTABLE_PATH jackin.role.toml'
    need_evidence 'throwaway/status.json' ''
    need_evidence 'throwaway/preflight.out' ''
    need_evidence 'throwaway/inside.out' ''
    finish
    ;;
  host)
    need_evidence 'verify.container.out' 'status: DONE'
    if [ "$fail" -ne 0 ]; then
      printf '%s\n' "container part has not passed"
      printf '%s\n' "status: PENDING"
      exit 1
    fi
    run_cmd 'jackin load donbeave/crew-operator probe-M1-05b --agent claude --mount ~/.jackin/agent-browser-profile:/home/agent/.agent-browser-profile'
    run_cmd 'docker logs <name>'
    run_cmd 'docker exec -u agent <name> sh -c '\''…'\'''
    run_cmd 'gh --version'
    run_cmd 'agent-browser --version'
    run_cmd 'python3 --version'
    run_cmd 'test -x /usr/bin/chromium'
    run_cmd 'agent-browser doctor --json'
    run_cmd 'agent-browser open about:blank'
    run_cmd '! command -v cargo'
    finish
    ;;
  *)
    printf '%s\n' "usage: $0 container|host"
    printf '%s\n' "status: PENDING"
    exit 2
    ;;
esac
